// <auto-generated />
using System;
using MaisVacina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaisVacina.Migrations
{
    [DbContext(typeof(MaisVacinaContext))]
    [Migration("20210701203610_Usuario")]
    partial class Usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MaisVacina.Models.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Email");

                    b.Property<string>("Endereço");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("MaisVacina.Models.Login", b =>
                {
                    b.Property<int>("Idlogin")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Emaillogin")
                        .IsRequired();

                    b.Property<string>("Nomelogin")
                        .IsRequired();

                    b.Property<string>("Senhalogin")
                        .IsRequired();

                    b.Property<string>("Usuario")
                        .IsRequired();

                    b.HasKey("Idlogin");

                    b.ToTable("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
